on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
name: Check

jobs:
  check:
    name: Check and lint
    runs-on: ubuntu-22.04 # FIXME: 24.04 missing libwebkit2gtk-4, required for Tauri
    steps: 
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Check build
        run: cargo check --all

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check lints
        run: cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test

      - name: Run test suite
        run: cd tests && python3 test.py
