on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Deploy

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk --version 0.21.12 --locked

      - name: Build
        run: trunk build --release
        working-directory: ./xdvdfs-web

      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy --project-name=xiso ./xdvdfs-web/dist
