on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
name: Nix

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    name: Build Nix Flake
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Build
        run: nix build
      - name: Check
        run: nix flake check
