on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
  schedule:
    - cron: '0 0 * * *'
name: Build (Features)

jobs:
  build_lib_no_std:
    name: Build (xdvdfs-no_std)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Check lints
        run: cargo clippy -p xdvdfs --no-default-features --features=read -- -D warnings

      - name: Build
        run: cargo build -p xdvdfs --no-default-features --features=read

      - name: Test
        run: cargo test -p xdvdfs --no-default-features --features=read

  build_lib_sync:
    name: Build (xdvdfs-sync)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Check lints
        run: cargo clippy -p xdvdfs --features=sync -- -D warnings

      - name: Build
        run: cargo build -p xdvdfs --features=sync
